spring:
  datasource:
#    driver: com.mysql.cj.jdbc.Driver
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
# 开启日志记录
logging:
  level:
    com.liaoin.dynamic.mybatis: trace